@HOST = http://localhost:8080

POST {{HOST}}/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY4ZDNlNWM3LTcxZDItNDcyMi05YzFkLWQ5ZDZkMWFhNWEwOCIsIm5hbWUiOiJFZHNvbiIsImVtYWlsIjoiZWRzb25AbWFydGlucy5jb20iLCJwcm9maWxlIjoiQURNSU4iLCJjb21wYW55IjpudWxsLCJpYXQiOjE2ODQyODY2NzAsImV4cCI6MTY4NDI5MDI3MH0.oMxe_OKA-l8mXDzGQ-XwLMoCCC-obEXh6Ce075P14Oo
Content-Type: application/json

{
  "name": "Edson",
  "email": "bobesponja@fendadobikini.com",
  "profile": "RECRUITER"
}

# {
#   "name": "Edson",
#   "email": "bobesponja@fendadobikini.com",
#   "profile": "RECRUITER",
#   "company": "Growdev"
# }
 