@HOST = http://localhost:8080

POST {{HOST}}/candidates HTTP/1.1
Content-Type: application/json

{
  "name": "Edson",
  "email": "lula@martins.com",
  "password": "password",
  "confirmPassword": "password"
}