@HOST = http://localhost:8080

POST {{HOST}}/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImExNjdhZTAzLWQ0NzQtNDk0Mi04M2FjLTYxYjUwMjY1M2FmNCIsIm5hbWUiOiJFZHNvbiIsImVtYWlsIjoid2luZHNvbkBsYS5jb20iLCJwcm9maWxlIjoiUkVDUlVJVEVSIiwiY29tcGFueSI6IlNTIiwiaWF0IjoxNjgzMjQyMDg4LCJleHAiOjE2ODMyNDU2ODh9.skMcwQdXCs4wTKZF2clL9_rTR0AeA7ixXvJZwUYQTMM
Content-Type: application/json

{
  "name": "Edson",
  "email": "bobesponja@fendadobikini.com",
  "profile": "RECRUITER"
}

# {
#   "name": "Edson",
#   "email": "bobesponja@fendadobikini.com",
#   "profile": "RECRUITER",
#   "company": "Growdev"
# }
 