@HOST = http://localhost:8080

GET  {{HOST}}/candidates HTTP/1.1

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ4OTRiYTExLWM2MWItNGZjNy04NTM5LThhNmNjYjA0MDA5YyIsIm5hbWUiOiJFZHNvbiIsImVtYWlsIjoid2luZHNvbkBtYXJ0aW5zLmNvbSIsInByb2ZpbGUiOiJDQU5ESURBVEUiLCJpYXQiOjE2ODMxNjMzMzcsImV4cCI6MTY4MzE2NjkzN30.P1c20OMyCfCPx9Hu2DuauAzhd6R-zrUH_s-VONUsTqU
Content-Type: application/json

{

}

 