@HOST = http://localhost:8080

GET  {{HOST}}/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY4ZDNlNWM3LTcxZDItNDcyMi05YzFkLWQ5ZDZkMWFhNWEwOCIsIm5hbWUiOiJFZHNvbiIsImVtYWlsIjoiZWRzb25AbWFydGlucy5jb20iLCJwcm9maWxlIjoiQURNSU4iLCJjb21wYW55IjpudWxsLCJpYXQiOjE2ODMyNDg5ODUsImV4cCI6MTY4MzI1MjU4NX0.8WaCsy5qtmA1tIPBNKNhT8NT7rfRSCk-LYP48UUvTFE

 