@HOST = http://localhost:8080

POST {{HOST}}/jobs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImExNjdhZTAzLWQ0NzQtNDk0Mi04M2FjLTYxYjUwMjY1M2FmNCIsIm5hbWUiOiJFZHNvbiIsImVtYWlsIjoid2luZHNvbkBsYS5jb20iLCJwcm9maWxlIjoiUkVDUlVJVEVSIiwiY29tcGFueSI6IlNTIiwiaWF0IjoxNjgzMjQyMzA4LCJleHAiOjE2ODMyNDU5MDh9.7gaHT0UYsexvUw0QdUTRGoYmzJiodDMPudSonCzZB2g

{
  "description": "dev jr",
  "limitDate": "2023-06-01",
  "maxCandidates": 1
}

